on: push

jobs:
  job_A:
    name: job A
    runs-on: ubuntu-latest
    steps:
      - name: job A step 1
        run: |
          echo "job A step 1"
      - name: job A step 2
        run: |
          echo "job A step 2"

  job_B:
    name: job B
    runs-on: ubuntu-latest
    steps:
      - name: job B step 1
        run: |
          echo "job B step 1"
