on: push

jobs:
  job_A:
    name: job A
    runs-on: ubuntu-latest
    steps:
      - name: job A step 1
        run: |
          echo "job A step 1"

      - name: job A step 2
        run: |
          echo "job A step 2"
          false

      - name: job A step 3
        if: failure()
        run: |
          echo "job A step 3"

      - name: job A step 4
        run: |
          echo "job A step 4"

  job_B:
    name: job B
    runs-on: ubuntu-latest
    steps:
      - name: job B step 1
        run: |
          echo "job B step 1"
          echo "job B" >> job_b.txt
          cat job_b.txt
      - name: job B step 2
        run: |
          echo "job B step 2"
          cat job_b.txt

  job_C:
    name: job C
    needs: job_A
    runs-on: ubuntu-latest
    steps:
      - name: job C step 1
        run: |
          echo "job C step 1"
